# .goreleaser.yaml
version: 2

project_name: kubemend

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Ignore invalid combinations (like windows/arm64 if not needed, though Go supports it)
    ignore:
      - goos: windows
        goarch: arm64
    binary: PromAI
    main: ./main.go

archives:
  - format: tar.gz
    # Use zip for windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
